### ISSUE TITLE
[Info] Devicelist Periodic Synchronization Process Proposal

### ISSUE THREAD

**Issue by zaia-siae** [openBackhaul/MicroWaveDeviceInventory#675]
Hi,
we are sharing you a document explaining how we would like to achieve the Devicelist Periodic Synchronization Process.
Let us know if ok.
[Device List Synchronization Proposal.pdf](https://github.com/openBackhaul/MicroWaveDeviceInventory/files/13296761/Device.List.Synchronization.Proposal.pdf)

**Comment by kmohr-soprasteria** [comment]
- For step2: please do not create a new deviceList but just modify the existing deviceList by adding new devices/removing no longer connected devices; we don't want to run into conflicts with the sync and possible changes due to notifications
- the new devices should be added right after the current position of the sliding window, so the CCs get retrieved with priority
  - see issue #511 and issues linked there for load balancing
  - as it is possible that there are many new devices from the same mediator due to mediator maintenance, we need to ensure some kind of load balancing
  - shuffling the deviceList parts in general is a first step, but we might need to somehow include mediator information
  - possibly we it would be better to only shuffle the deviceList if it is retrieved for the first time and then later just shuffle the segment of new devices (of course if the deviceList gets emptied due to Controller outage, we might want to shuffle again)
    - why do it in that way? because if we do it like that we ensure that the CCs are more or less requested in the same order than in previous retrieval periods and we don't end up retrieving a CC "too early". (E.g. assume it has just been retrieved half an hour ago and after shuffling it would be retrieved just now again, while others have been retrieved like 6 hours ago and have been moved to the end of the deviceList and would need to wait for another 6 hours to get retrieved again.)
