### ISSUE TITLE
API is missing for controller object creation and controller object deletion

### ISSUE THREAD

**Issue by Ziabatcha** [openBackhaul/MicroWaveDeviceInventory#774]
Currently notification proxy notify the controller object create notification to subscriber through API:/v1/regard-controller-object-creation.
But MWDI doesnt have API:/v1/regard-controller-object-creation. 

Similarly API is missing for object delete notification in MWDI API:/v1/regard-controller-object-deletion. 

Is above missing APIs are handled by existing available API:/v1/regard-controller-attribute-value-change ? or need to add missing API in specification ?

**Comment by kmohr-soprasteria** [comment]
The MWDI doesn't need to know if a new device is added to the Controller or if one is deleted explicitly. It only needs to be aware of connection-state changes.
I.e. if it receives the information that deviceA has changed into "connected" state, then deviceA will get added to MWDI; but if MWDI receives the information that for deviceA the connection state has changed from "connected" to something else, it will get removed from MWDI.
(In case that we e.g. would not receive all notifications, we could get into an asynchronous state, that's why we also do a sync with the list of connected devices from the Controller periodically.) 

So there's no need for adding additional services.

**Comment by Ziabatcha** [comment]
Thanks for the detailed information, based on the comments closing this issue
