### ISSUE TITLE
MWDi is accepting all operation key

### ISSUE THREAD

**Issue by Ziabatcha** [openBackhaul/MicroWaveDeviceInventory#829]
When user tried to send any API request from MWDI with any operation key value, request is getting successfull which is not correct.

**Comment by nardecchia-siae** [comment]
To enable the parsing of operation keys it is necessary to uncomment in the index.js file the openApiValidator.
There is an issue #366 which reports a problem in the validation process of the control constructs.
We're waiting for a fix in the yaml file to generate a nodejs server api that allow us to enable the openApiValidator otherwise all the responses from all the APIs will fail.

**Comment by nardecchia-siae** [comment]
Issue fixed disabling the validation of the control constructs

**Comment by Ziabatcha** [comment]
Issue verified and closed in test_v1.1.3
